---
title: "Building 2dii-like packages"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  comment = "#>",
  error = TRUE,
  collapse = TRUE
)
```

The goal of this article is to show how to build r2dii-like packages. All code should run in R (default), or a Unix-like terminal (commented with `# bash`).

For a more general explanation see https://r-pkgs.org/whole-game.html.

## Setup

* Setup a GitHub repo, clone it, and setup the remote: and link it to RStudio
    * On GitHub create a new repository. Name it exactly as the package.
    * Copy the clone URL.
    * On RStudio create a _New Project ...> Version Control_.

* Transform the project into an R package.

```r
usethis::create_package("../r2dii.packagename")
```

* A new RStudio session will open automatically.

## Add minimal infrastructure

* Attach useful packages.

```r
library(r2dii.usethis)
library(usethis)
library(devtools)
```

* For public packages add a common license (see `?usethis::use_*_license()`).

```r
use_gpl3_license()
```

* For private packages maybe add "Private package" in a `LICENSE` file at the root.

```bash
# bash
echo "Private package." > LICENSE
```

* Allow opening the GitHub repo with `browse_github()`.

```
use_github_links()
```

* Enable markdown syntax in R documentation.

```
use_roxygen_md()
```

* Edit the DESCRIPTION file manually.
* Tidy DESCRIPTION.

```
use_tidy_description()
```

* Check.

```r
# Control + Shift + E
check()
```

* Confirm that R CMD check runs with 0 errors, 0 warnings, and 0 notes.

* On GitHub consider tweaking collaboration and branch settings. For example:
    
    * Add a rule for branches matching the pattern "master", and
    * Restrict who can push to matching branches.

```
browse_github()
```

## Extend infrastructure with templates

  * Install the package.

```
install()
```

* Create README.Rmd from a template.

```r
# Setup readme (e.g. adds a line to .buildignore)
usethis::use_readme_rmd()

# Overwrite pre-existing file 'README.Rmd' with r2dii's template
use_template("README.Rmd", package = "r2dii.usethis")

use_cran_badge()
```

* Edit README.Rmd manually.

* Spellcheck.

* Knit README.Rmd.

* Check that R CMD check results in 0 errors, warnings, and messages.

```
check()
```

* Commit and push.

## What else?

The r2dii.usethis includes many more [templates](https://github.com/2DegreesInvesting/r2dii.usethis/tree/master/inst/templates)

For inspiration you may also see [this post](https://fgeo.netlify.com/2018/03/28/2018-03-28-building-infrastructure-for-r-packages-with-usethis/)

The ultimate source is the R packages book:

* [First edition](http://r-pkgs.had.co.nz/).
* [Second edition](https://r-pkgs.org/) (work in progress; includes usethis).
